services:
  - name: frontend
    build: echo "Building in start script to ensure persistence"
    start: npm install --legacy-peer-deps && CI=false npm run build && npx serve -l 3000
    path: ./frontend
    port: 3000

  - name: backend
    build: echo "Skipping pip install for connectivity test"
    start: python3 -m http.server 8080
    path: ./backend
    port: 8080
routes:
  - path: /api
    service: backend
  - path: /
    service: frontend
