services:
  - name: frontend
    build: echo "Building in start script to ensure persistence"
    start: npm install --legacy-peer-deps && CI=false npm run build && npx serve -s build -l 3000
    path: ./frontend
    port: 3000

  - name: backend
    build: echo "Skipping build step"
    start: pip install -r requirements.txt && uvicorn server:app --host 0.0.0.0 --port 8080
    path: ./backend
    port: 8080
routes:
  - path: /api
    service: backend
  - path: /
    service: frontend
