services:
  - name: frontend
    build: CI=false npm run build
    start: npx serve -s build -l 3000
    path: ./frontend
    port: 3000

  - name: backend
    build: pip install -r requirements.txt
    start: uvicorn server:app --host 0.0.0.0 --port 4000
    path: ./backend
    port: 4000
routes:
  - path: /api
    service: backend
  - path: /
    service: frontend
