services:
  - name: frontend
    build: npm run build
    start: npm run preview
    path: ./frontend
    port: 3000

  - name: backend
    build: npm install
    start: node server.js
    path: ./backend
    port: 4000
routes:
  - path: /api
    service: backend
  - path: /
    service: frontend
